// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKw2y9TLvVq9hBXY36SGh278FxzvIunDo',
    appId: '1:386904137640:web:6d542923d8d276e3d2c79d',
    messagingSenderId: '386904137640',
    projectId: 'projet-web-2-43762',
    authDomain: 'projet-web-2-43762.firebaseapp.com',
    storageBucket: 'projet-web-2-43762.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBca4-aqT1Wkn6I4TUKJbvUhV18RPQbEnk',
    appId: '1:386904137640:android:a191bc73ebbe2d46d2c79d',
    messagingSenderId: '386904137640',
    projectId: 'projet-web-2-43762',
    storageBucket: 'projet-web-2-43762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_3aTfxeldVF89yQlUxWWcUayDtE8kyI',
    appId: '1:386904137640:ios:ab41f778ec82c888d2c79d',
    messagingSenderId: '386904137640',
    projectId: 'projet-web-2-43762',
    storageBucket: 'projet-web-2-43762.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_3aTfxeldVF89yQlUxWWcUayDtE8kyI',
    appId: '1:386904137640:ios:ab41f778ec82c888d2c79d',
    messagingSenderId: '386904137640',
    projectId: 'projet-web-2-43762',
    storageBucket: 'projet-web-2-43762.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKw2y9TLvVq9hBXY36SGh278FxzvIunDo',
    appId: '1:386904137640:web:b4bf708e2f98acced2c79d',
    messagingSenderId: '386904137640',
    projectId: 'projet-web-2-43762',
    authDomain: 'projet-web-2-43762.firebaseapp.com',
    storageBucket: 'projet-web-2-43762.firebasestorage.app',
  );
}
